// src/resources/js/components/vue/ProofOfWork.vue
<template>
  <div>
    <button @click="getChallenge" :disabled="working">Get Challenge</button>
    <p v-if="challenge">Challenge: {{ challenge }}</p>
    <p v-if="difficulty !== null">Difficulty: {{ difficulty }}</p>
    <p v-if="proof">Proof: {{ proof }}</p>
    <p v-if="status">Status: {{ status }}</p>
  </div>
</template>

<script>
export default {
  data() {
    return {
      challenge: null,
      difficulty: null,
      proof: null,
      status: null,
      working: false,
    };
  },
  methods: {
    async getChallenge() {
      this.working = true;
      try {
        const response = await fetch('/api/pow/challenge');
        const data = await response.json();
        this.challenge = data.challenge;
        this.difficulty = data.difficulty;
        this.calculateProof();
      } catch (error) {
        console.error('Error fetching challenge:', error);
      }
    },
    async calculateProof() {
      let nonce = 0;
      while (!this.verifyProof(this.challenge, nonce.toString())) {
        nonce++;
      }
      this.proof = nonce.toString();
      this.verifyWithServer();
    },
    verifyProof(challenge, proof) {
      const hash = this.sha256(challenge + proof);
      return hash.startsWith('0'.repeat(this.difficulty));
    },
    async verifyWithServer() {
      try {
        const response = await fetch('/api/pow/verify', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({ challenge: this.challenge, proof: this.proof }),
        });
        const data = await response.json();
        this.status = data.status;
      } catch (error) {
        console.error('Error verifying proof:', error);
      } finally {
        this.working = false;
      }
    },
    async sha256(message) {
      const msgBuffer = new TextEncoder().encode(message);
      const hashBuffer = await crypto.subtle.digest('SHA-256', msgBuffer);
      const hashArray = Array.from(new Uint8Array(hashBuffer));
      return hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
    },
  },
};
</script>

// src/resources/js/components/react/ProofOfWork.jsx
import React, { useState, useEffect } from 'react';

const ProofOfWork = () => {
  const [challenge, setChallenge] = useState(null);
  const [difficulty, setDifficulty] = useState(null);
  const [proof, setProof] = useState(null);
  const [status, setStatus] = useState(null);
  const [working, setWorking] = useState(false);

  const getChallenge = async () => {
    setWorking(true);
    try {
      const response = await fetch('/api/pow/challenge');
      const data = await response.json();
      setChallenge(data.challenge);
      setDifficulty(data.difficulty);
      calculateProof(data.challenge, data.difficulty);
    } catch (error) {
      console.error('Error fetching challenge:', error);
    }
  };

  const calculateProof = (challenge, difficulty) => {
    let nonce = 0;
    while (!verifyProof(challenge, nonce.toString(), difficulty)) {
      nonce++;
    }
    setProof(nonce.toString());
    verifyWithServer(challenge, nonce.toString());
  };

  const verifyProof = (challenge, proof, difficulty) => {
    const hash = sha256(challenge + proof);
    return hash.startsWith('0'.repeat(difficulty));
  };

  const verifyWithServer = async (challenge, proof) => {
    try {
      const response = await fetch('/api/pow/verify', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ challenge, proof }),
      });
      const data = await response.json();
      setStatus(data.status);
    } catch (error) {
      console.error('Error verifying proof:', error);
    } finally {
      setWorking(false);
    }
  };

  const sha256 = async (message) => {
    const msgBuffer = new TextEncoder().encode(message);
    const hashBuffer = await crypto.subtle.digest('SHA-256', msgBuffer);
    const hashArray = Array.from(new Uint8Array(hashBuffer));
    return hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
  };

  return (
    <div>
      <button onClick={getChallenge} disabled={working}>Get Challenge</button>
      {challenge && <p>Challenge: {challenge}</p>}
      {difficulty !== null && <p>Difficulty: {difficulty}</p>}
      {proof && <p>Proof: {proof}</p>}
      {status && <p>Status: {status}</p>}
    </div>
  );
};

export default ProofOfWork;
